#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : konversation
Version  : 1.7.5
Release  : 1
URL      : https://download.kde.org/stable/konversation/1.7.5/src/konversation-1.7.5.tar.xz
Source0  : https://download.kde.org/stable/konversation/1.7.5/src/konversation-1.7.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
Requires: konversation-bin = %{version}-%{release}
Requires: konversation-data = %{version}-%{release}
Requires: konversation-license = %{version}-%{release}
Requires: konversation-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kglobalaccel-dev
BuildRequires : kidletime-dev
BuildRequires : knotifyconfig-dev
BuildRequires : phonon-dev
BuildRequires : qca-qt5-dev
BuildRequires : qtbase-dev mesa-dev

%description
Konversation website: http://konversation.kde.org/
Konversation wiki: http://userbase.kde.org/Konversation
Bug tracker: https://bugs.kde.org/
IRC channel: #konversation on chat.freenode.net

%package bin
Summary: bin components for the konversation package.
Group: Binaries
Requires: konversation-data = %{version}-%{release}
Requires: konversation-license = %{version}-%{release}

%description bin
bin components for the konversation package.


%package data
Summary: data components for the konversation package.
Group: Data

%description data
data components for the konversation package.


%package doc
Summary: doc components for the konversation package.
Group: Documentation

%description doc
doc components for the konversation package.


%package license
Summary: license components for the konversation package.
Group: Default

%description license
license components for the konversation package.


%package locales
Summary: locales components for the konversation package.
Group: Default

%description locales
locales components for the konversation package.


%prep
%setup -q -n konversation-1.7.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542149602
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1542149602
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/konversation
cp COPYING %{buildroot}/usr/share/package-licenses/konversation/COPYING
cp COPYING-DOCS %{buildroot}/usr/share/package-licenses/konversation/COPYING-DOCS
pushd clr-build
%make_install
popd
%find_lang konversation

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/konversation

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.konversation.desktop
/usr/share/icons/hicolor/128x128/actions/konv_message.png
/usr/share/icons/hicolor/128x128/apps/konversation.png
/usr/share/icons/hicolor/16x16/actions/konv_message.png
/usr/share/icons/hicolor/16x16/apps/konversation.png
/usr/share/icons/hicolor/22x22/actions/konv_message.png
/usr/share/icons/hicolor/22x22/apps/konversation.png
/usr/share/icons/hicolor/32x32/actions/konv_message.png
/usr/share/icons/hicolor/32x32/apps/konversation.png
/usr/share/icons/hicolor/48x48/actions/konv_message.png
/usr/share/icons/hicolor/48x48/apps/konversation.png
/usr/share/icons/hicolor/64x64/actions/konv_message.png
/usr/share/icons/hicolor/64x64/apps/konversation.png
/usr/share/kconf_update/konversation-0.19-appearance.pl
/usr/share/kconf_update/konversation-0.19-colorcodes.pl
/usr/share/kconf_update/konversation-0.19-colors.pl
/usr/share/kconf_update/konversation-0.19-custombrowser.pl
/usr/share/kconf_update/konversation-0.19-notifylists.pl
/usr/share/kconf_update/konversation-0.19-sortorder.pl
/usr/share/kconf_update/konversation-0.19-tabplacement.pl
/usr/share/kconf_update/konversation-0.20-customfonts.pl
/usr/share/kconf_update/konversation-0.20-quickbuttons.pl
/usr/share/kconf_update/konversation.upd
/usr/share/knotifications5/konversation.notifyrc
/usr/share/konversation/scripting_support/python/konversation/__init__.py
/usr/share/konversation/scripting_support/python/konversation/dbus.py
/usr/share/konversation/scripting_support/python/konversation/i18n.py
/usr/share/konversation/scripts/bug
/usr/share/konversation/scripts/cmd
/usr/share/konversation/scripts/fortune
/usr/share/konversation/scripts/fortunes.dat
/usr/share/konversation/scripts/gauge
/usr/share/konversation/scripts/mail
/usr/share/konversation/scripts/media
/usr/share/konversation/scripts/sayclip
/usr/share/konversation/scripts/sysinfo
/usr/share/konversation/scripts/tinyurl
/usr/share/konversation/scripts/uptime
/usr/share/konversation/themes/alternative/index.desktop
/usr/share/konversation/themes/alternative/irc_admin.png
/usr/share/konversation/themes/alternative/irc_away.png
/usr/share/konversation/themes/alternative/irc_halfop.png
/usr/share/konversation/themes/alternative/irc_normal.png
/usr/share/konversation/themes/alternative/irc_op.png
/usr/share/konversation/themes/alternative/irc_owner.png
/usr/share/konversation/themes/alternative/irc_voice.png
/usr/share/konversation/themes/christmas/index.desktop
/usr/share/konversation/themes/christmas/irc_admin.png
/usr/share/konversation/themes/christmas/irc_away.png
/usr/share/konversation/themes/christmas/irc_halfop.png
/usr/share/konversation/themes/christmas/irc_normal.png
/usr/share/konversation/themes/christmas/irc_op.png
/usr/share/konversation/themes/christmas/irc_owner.png
/usr/share/konversation/themes/christmas/irc_voice.png
/usr/share/konversation/themes/classic/index.desktop
/usr/share/konversation/themes/classic/irc_admin.png
/usr/share/konversation/themes/classic/irc_away.png
/usr/share/konversation/themes/classic/irc_halfop.png
/usr/share/konversation/themes/classic/irc_normal.png
/usr/share/konversation/themes/classic/irc_op.png
/usr/share/konversation/themes/classic/irc_owner.png
/usr/share/konversation/themes/classic/irc_voice.png
/usr/share/konversation/themes/default/index.desktop
/usr/share/konversation/themes/default/irc_admin.png
/usr/share/konversation/themes/default/irc_away.png
/usr/share/konversation/themes/default/irc_away_stacked.png
/usr/share/konversation/themes/default/irc_halfop.png
/usr/share/konversation/themes/default/irc_normal.png
/usr/share/konversation/themes/default/irc_op.png
/usr/share/konversation/themes/default/irc_owner.png
/usr/share/konversation/themes/default/irc_voice.png
/usr/share/konversation/themes/oxygen/index.desktop
/usr/share/konversation/themes/oxygen/irc_admin.png
/usr/share/konversation/themes/oxygen/irc_away.png
/usr/share/konversation/themes/oxygen/irc_halfop.png
/usr/share/konversation/themes/oxygen/irc_normal.png
/usr/share/konversation/themes/oxygen/irc_op.png
/usr/share/konversation/themes/oxygen/irc_owner.png
/usr/share/konversation/themes/oxygen/irc_voice.png
/usr/share/konversation/themes/simplistic/index.desktop
/usr/share/konversation/themes/simplistic/irc_admin.png
/usr/share/konversation/themes/simplistic/irc_away.png
/usr/share/konversation/themes/simplistic/irc_halfop.png
/usr/share/konversation/themes/simplistic/irc_normal.png
/usr/share/konversation/themes/simplistic/irc_op.png
/usr/share/konversation/themes/simplistic/irc_owner.png
/usr/share/konversation/themes/simplistic/irc_voice.png
/usr/share/konversation/themes/smiling/index.desktop
/usr/share/konversation/themes/smiling/irc_admin.png
/usr/share/konversation/themes/smiling/irc_away.png
/usr/share/konversation/themes/smiling/irc_halfop.png
/usr/share/konversation/themes/smiling/irc_normal.png
/usr/share/konversation/themes/smiling/irc_op.png
/usr/share/konversation/themes/smiling/irc_owner.png
/usr/share/konversation/themes/smiling/irc_voice.png
/usr/share/konversation/themes/square/index.desktop
/usr/share/konversation/themes/square/irc_admin.png
/usr/share/konversation/themes/square/irc_away.png
/usr/share/konversation/themes/square/irc_halfop.png
/usr/share/konversation/themes/square/irc_normal.png
/usr/share/konversation/themes/square/irc_op.png
/usr/share/konversation/themes/square/irc_owner.png
/usr/share/konversation/themes/square/irc_voice.png
/usr/share/kxmlgui5/konversation/konversationui.rc
/usr/share/metainfo/org.kde.konversation.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/konversation/addchannel.png
/usr/share/doc/HTML/ca/konversation/addnetwork_co.png
/usr/share/doc/HTML/ca/konversation/addserver_co.png
/usr/share/doc/HTML/ca/konversation/channel_screen_tour_co.png
/usr/share/doc/HTML/ca/konversation/channellist_screen_co.png
/usr/share/doc/HTML/ca/konversation/first_channel_co.png
/usr/share/doc/HTML/ca/konversation/first_serverlist_co.png
/usr/share/doc/HTML/ca/konversation/format-text-color.png
/usr/share/doc/HTML/ca/konversation/highlighting_screen_co.png
/usr/share/doc/HTML/ca/konversation/identities_adv_co.png
/usr/share/doc/HTML/ca/konversation/identities_away_co.png
/usr/share/doc/HTML/ca/konversation/identities_gen_co.png
/usr/share/doc/HTML/ca/konversation/index.cache.bz2
/usr/share/doc/HTML/ca/konversation/index.docbook
/usr/share/doc/HTML/ca/konversation/irc_admin.png
/usr/share/doc/HTML/ca/konversation/irc_away.png
/usr/share/doc/HTML/ca/konversation/irc_halfop.png
/usr/share/doc/HTML/ca/konversation/irc_normal.png
/usr/share/doc/HTML/ca/konversation/irc_op.png
/usr/share/doc/HTML/ca/konversation/irc_owner.png
/usr/share/doc/HTML/ca/konversation/irc_voice.png
/usr/share/doc/HTML/ca/konversation/led_blue_on.png
/usr/share/doc/HTML/ca/konversation/led_green_on.png
/usr/share/doc/HTML/ca/konversation/led_red_on.png
/usr/share/doc/HTML/ca/konversation/led_yellow_on.png
/usr/share/doc/HTML/ca/konversation/logviewer_co.png
/usr/share/doc/HTML/ca/konversation/nicksonline_co.png
/usr/share/doc/HTML/ca/konversation/nickthemes_screen_co.png
/usr/share/doc/HTML/ca/konversation/notification_screen_co.png
/usr/share/doc/HTML/ca/konversation/notifylist_screen_co.png
/usr/share/doc/HTML/ca/konversation/osd_screen_co.png
/usr/share/doc/HTML/ca/konversation/quickbuttons_screen.png
/usr/share/doc/HTML/ca/konversation/quickconnect_screen.png
/usr/share/doc/HTML/ca/konversation/serverlist_co.png
/usr/share/doc/HTML/ca/konversation/urlcatcher_screen_co.png
/usr/share/doc/HTML/ca/konversation/webbrowser_screen_co.png
/usr/share/doc/HTML/de/konversation/index.cache.bz2
/usr/share/doc/HTML/de/konversation/index.docbook
/usr/share/doc/HTML/en/konversation/addchannel.png
/usr/share/doc/HTML/en/konversation/addnetwork_co.png
/usr/share/doc/HTML/en/konversation/addserver_co.png
/usr/share/doc/HTML/en/konversation/bold-text.png
/usr/share/doc/HTML/en/konversation/channel_screen_tour_co.png
/usr/share/doc/HTML/en/konversation/channellist_screen_co.png
/usr/share/doc/HTML/en/konversation/checkidentities.png
/usr/share/doc/HTML/en/konversation/colorchooser_screen.png
/usr/share/doc/HTML/en/konversation/dccstatus_screen_co.png
/usr/share/doc/HTML/en/konversation/first_channel_co.png
/usr/share/doc/HTML/en/konversation/first_serverlist_co.png
/usr/share/doc/HTML/en/konversation/format-text-color.png
/usr/share/doc/HTML/en/konversation/highlighting_screen_co.png
/usr/share/doc/HTML/en/konversation/identities_adv_co.png
/usr/share/doc/HTML/en/konversation/identities_away_co.png
/usr/share/doc/HTML/en/konversation/identities_gen_co.png
/usr/share/doc/HTML/en/konversation/index.cache.bz2
/usr/share/doc/HTML/en/konversation/index.docbook
/usr/share/doc/HTML/en/konversation/irc_admin.png
/usr/share/doc/HTML/en/konversation/irc_away.png
/usr/share/doc/HTML/en/konversation/irc_halfop.png
/usr/share/doc/HTML/en/konversation/irc_normal.png
/usr/share/doc/HTML/en/konversation/irc_op.png
/usr/share/doc/HTML/en/konversation/irc_owner.png
/usr/share/doc/HTML/en/konversation/irc_voice.png
/usr/share/doc/HTML/en/konversation/italic-text.png
/usr/share/doc/HTML/en/konversation/led_blue_on.png
/usr/share/doc/HTML/en/konversation/led_green_on.png
/usr/share/doc/HTML/en/konversation/led_red_on.png
/usr/share/doc/HTML/en/konversation/led_yellow_on.png
/usr/share/doc/HTML/en/konversation/logviewer_co.png
/usr/share/doc/HTML/en/konversation/nicksonline_co.png
/usr/share/doc/HTML/en/konversation/nickthemes_screen_co.png
/usr/share/doc/HTML/en/konversation/notification_screen_co.png
/usr/share/doc/HTML/en/konversation/notifylist_screen_co.png
/usr/share/doc/HTML/en/konversation/osd_demo.png
/usr/share/doc/HTML/en/konversation/osd_screen_co.png
/usr/share/doc/HTML/en/konversation/quickbuttons_screen.png
/usr/share/doc/HTML/en/konversation/quickconnect_screen.png
/usr/share/doc/HTML/en/konversation/serverlist_co.png
/usr/share/doc/HTML/en/konversation/struck-out-text.png
/usr/share/doc/HTML/en/konversation/underline-text.png
/usr/share/doc/HTML/en/konversation/urlcatcher_screen_co.png
/usr/share/doc/HTML/en/konversation/webbrowser_screen_co.png
/usr/share/doc/HTML/es/konversation/index.cache.bz2
/usr/share/doc/HTML/es/konversation/index.docbook
/usr/share/doc/HTML/it/konversation/index.cache.bz2
/usr/share/doc/HTML/it/konversation/index.docbook
/usr/share/doc/HTML/nl/konversation/index.cache.bz2
/usr/share/doc/HTML/nl/konversation/index.docbook
/usr/share/doc/HTML/pt_BR/konversation/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konversation/index.docbook
/usr/share/doc/HTML/sv/konversation/addchannel.png
/usr/share/doc/HTML/sv/konversation/addnetwork_co.png
/usr/share/doc/HTML/sv/konversation/addserver_co.png
/usr/share/doc/HTML/sv/konversation/channel_screen_tour_co.png
/usr/share/doc/HTML/sv/konversation/channellist_screen_co.png
/usr/share/doc/HTML/sv/konversation/checkidentities.png
/usr/share/doc/HTML/sv/konversation/colorchooser_screen.png
/usr/share/doc/HTML/sv/konversation/dccstatus_screen_co.png
/usr/share/doc/HTML/sv/konversation/first_channel_co.png
/usr/share/doc/HTML/sv/konversation/first_serverlist_co.png
/usr/share/doc/HTML/sv/konversation/highlighting_screen_co.png
/usr/share/doc/HTML/sv/konversation/identities_adv_co.png
/usr/share/doc/HTML/sv/konversation/identities_away_co.png
/usr/share/doc/HTML/sv/konversation/identities_gen_co.png
/usr/share/doc/HTML/sv/konversation/index.cache.bz2
/usr/share/doc/HTML/sv/konversation/index.docbook
/usr/share/doc/HTML/sv/konversation/kimproxy_create_screen2.png
/usr/share/doc/HTML/sv/konversation/kimproxy_create_screen_co.png
/usr/share/doc/HTML/sv/konversation/logviewer_co.png
/usr/share/doc/HTML/sv/konversation/nicksonline_co.png
/usr/share/doc/HTML/sv/konversation/nickthemes_screen_co.png
/usr/share/doc/HTML/sv/konversation/notification_screen_co.png
/usr/share/doc/HTML/sv/konversation/notifylist_screen_co.png
/usr/share/doc/HTML/sv/konversation/osd_demo.png
/usr/share/doc/HTML/sv/konversation/osd_screen_co.png
/usr/share/doc/HTML/sv/konversation/quickbuttons_screen.png
/usr/share/doc/HTML/sv/konversation/quickconnect_screen.png
/usr/share/doc/HTML/sv/konversation/serverlist_co.png
/usr/share/doc/HTML/sv/konversation/urlcatcher_screen_co.png
/usr/share/doc/HTML/sv/konversation/webbrowser_screen_co.png
/usr/share/doc/HTML/uk/konversation/index.cache.bz2
/usr/share/doc/HTML/uk/konversation/index.docbook

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/konversation/COPYING
/usr/share/package-licenses/konversation/COPYING-DOCS

%files locales -f konversation.lang
%defattr(-,root,root,-)

